name: Build & Test for Apple Platforms

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Validate the package manifest and lint the code style
  validate-and-lint:
    name: Validate & Lint
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Package Manifest
        run: swift package describe

      - name: Install swift-format
        run: brew install swift-format

      - name: Check Code Formatting
        run: swift-format lint . --recursive
        
  # Build and test the package across multiple platforms and Xcode versions
  build-and-test:
    name: Build & Test (${{ matrix.destination }})
    runs-on: macos-latest
    
    # Use a matrix to define all the build configurations
    strategy:
      fail-fast: false
      matrix:
        destination:
          - "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2"
          - "platform=macOS,arch=arm64"
          - "platform=visionOS Simulator,name=Apple Vision Pro,OS=2.2" 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      - name: Select latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Show current version of Xcode
        run: xcodebuild -version

      # Build and test
      - name: Run Tests
        run: |
          set -o pipefail
          xcodebuild test \
            -scheme "WaveformScrubber" \
            -destination "${{ matrix.destination }}"

      # Build the example app
      - name: Build Example App
        if: matrix.destination == 'platform=iOS Simulator,name=iPhone 16 Pro'
        run: |
          xcodebuild build \
            -scheme WaveformScrubberExample \
            -destination "${{ matrix.destination }}" \
            -project Example/WaveformScrubberExample.xcodeproj
